import { StyleSheet } from "react-native";

export const palette = {
  bg: "#F3E7D8",
  surface: "#FFF8F1",
  ink: "#2A1C16",
  muted: "#7A6458",
  rose: "#C45C4A",
  gold: "#C4A36A",
  line: "#E4D2C0",
  cream: "#EFE3D6",
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: palette.bg },
  scroll: { padding: 20, paddingBottom: 48 },
  kicker: {
    color: "#9E3F34",
    letterSpacing: 2,
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: "600",
  },
  title: {
    fontFamily: "Georgia",
    fontSize: 34,
    lineHeight: 38,
    color: palette.ink,
    marginTop: 8,
    marginBottom: 10,
  },
  lede: { color: palette.muted, fontSize: 16, lineHeight: 24, marginBottom: 18 },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 22,
    padding: 18,
    marginBottom: 12,
    shadowColor: "#502A1C",
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  cardTitle: { fontFamily: "Georgia", fontSize: 22, color: palette.ink, marginBottom: 6 },
  cardBody: { color: palette.muted, lineHeight: 22 },
  primary: {
    backgroundColor: palette.ink,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    marginTop: 8,
  },
  primaryText: { color: "#FFFCFA", fontWeight: "600" },
  secondary: {
    backgroundColor: palette.surface,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    marginTop: 8,
    borderWidth: 1,
    borderColor: palette.line,
  },
  secondaryText: { color: palette.ink, fontWeight: "600" },
  ghostText: { color: palette.muted, textAlign: "center", marginTop: 14 },
  choice: {
    backgroundColor: palette.surface,
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  choiceOn: { borderColor: palette.ink, backgroundColor: "#fff" },
  choiceLabel: { fontWeight: "600", color: palette.ink, marginBottom: 4 },
  choiceHint: { color: palette.muted, fontSize: 13 },
  row: { flexDirection: "row", justifyContent: "space-between", gap: 10, marginTop: 12 },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipOn: { backgroundColor: palette.ink, borderColor: palette.ink },
  chipText: { color: palette.ink },
  chipTextOn: { color: "#FFFCFA" },
  input: {
    backgroundColor: palette.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: palette.line,
    color: palette.ink,
    marginTop: 8,
  },
  num: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: palette.ink,
    color: "#FFF8F1",
    textAlign: "center",
    textAlignVertical: "center",
    fontFamily: "Georgia",
    fontSize: 18,
    lineHeight: 34,
    overflow: "hidden",
  },
  look: {
    backgroundColor: palette.cream,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 6,
    color: palette.ink,
    fontSize: 12,
    overflow: "hidden",
  },
  product: { backgroundColor: "#FBF1E6", borderRadius: 14, padding: 12, marginTop: 8 },
  error: { color: "#9E3F34", marginTop: 10, lineHeight: 20 },
  preview: { width: "100%", height: 320, borderRadius: 22, marginVertical: 12, backgroundColor: "#1D1410" },
});
