import type { CatalogProduct } from "./types";

export const CATALOG: CatalogProduct[] = [
  // —— Skin · Cleansers ——
  {
    id: "cerave-hydrating-cleanser",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    area: "skin",
    category: "Cream cleanser",
    step: "cleanser",
    budget: "drugstore",
    lookFor: ["ceramides", "hyaluronic acid", "fragrance-free", "non-foaming"],
    why: "Takes makeup-light dirt off without stripping a dry or sensitive barrier.",
    skinTypes: ["dry", "normal", "sensitive", "combination"],
    skinConcerns: ["dryness", "redness", "fine-lines"],
    avoidSkinTypes: ["oily"],
  },
  {
    id: "cerave-foaming-cleanser",
    name: "Foaming Facial Cleanser",
    brand: "CeraVe",
    area: "skin",
    category: "Gel cleanser",
    step: "cleanser",
    budget: "drugstore",
    lookFor: ["ceramides", "niacinamide", "foaming", "fragrance-free"],
    why: "A gentle foam that respects oilier and combination skin without a squeak.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["oiliness", "acne", "pores"],
  },
  {
    id: "lrp-toleriane-cleanser",
    name: "Toleriane Hydrating Gentle Cleanser",
    brand: "La Roche-Posay",
    area: "skin",
    category: "Cream cleanser",
    step: "cleanser",
    budget: "mid",
    lookFor: ["niacinamide", "ceramides", "prebiotic thermal water", "fragrance-free"],
    why: "A quiet wash for reactive, redness-prone, or post-active nights.",
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    skinConcerns: ["redness", "dryness"],
  },
  {
    id: "fresh-soy-cleanser",
    name: "Soy Face Cleanser",
    brand: "Fresh",
    area: "skin",
    category: "Gel-cream cleanser",
    step: "cleanser",
    budget: "splurge",
    lookFor: ["soy proteins", "cucumber", "pH-balanced", "makeup-removing"],
    why: "A silky everyday cleanse that still feels like a treatment, not a strip.",
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    skinConcerns: ["dullness", "dryness"],
  },
  {
    id: "panoxyl-cleanser",
    name: "Acne Foaming Wash 4%",
    brand: "PanOxyl",
    area: "skin",
    category: "Benzoyl peroxide wash",
    step: "cleanser",
    budget: "drugstore",
    lookFor: ["benzoyl peroxide 4%", "foaming", "short contact"],
    why: "A targeted wash on breakout days — not a 60-second everyday scrub.",
    skinTypes: ["oily", "combination"],
    skinConcerns: ["acne"],
    avoidSkinTypes: ["dry", "sensitive"],
  },
  {
    id: "tatcha-rice-wash",
    name: "The Rice Wash",
    brand: "Tatcha",
    area: "skin",
    category: "Cream cleanser",
    step: "cleanser",
    budget: "splurge",
    lookFor: ["Japanese rice bran", "hyaluronic acid", "creamy lather"],
    why: "Polish without grit — a luxury cleanse that keeps glow on dry skin.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dullness", "dryness", "texture"],
  },
  {
    id: "innisfree-green-tea-cleanser",
    name: "Green Tea Hydrating Amino Acid Cleanser",
    brand: "innisfree",
    area: "skin",
    category: "Gel cleanser",
    step: "cleanser",
    budget: "mid",
    lookFor: ["amino acids", "green tea", "low-foam", "pH-balanced"],
    why: "A light gel that respects combination skin and morning oil.",
    skinTypes: ["combination", "oily", "normal"],
    skinConcerns: ["oiliness", "dullness", "pores"],
  },

  // —— Skin · Exfoliant ——
  {
    id: "pc-bha-liquid",
    name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    area: "skin",
    category: "Leave-on BHA",
    step: "exfoliant",
    budget: "mid",
    lookFor: ["salicylic acid 2%", "leave-on", "blackhead-friendly"],
    why: "The classic pore-clearing acid for congestion, texture, and stubborn shine.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["pores", "acne", "texture", "oiliness", "dullness"],
    avoidSkinTypes: ["sensitive"],
  },
  {
    id: "to-lactic-acid",
    name: "Lactic Acid 5% + HA",
    brand: "The Ordinary",
    area: "skin",
    category: "AHA serum",
    step: "exfoliant",
    budget: "drugstore",
    lookFor: ["lactic acid 5%", "hyaluronic acid", "night use"],
    why: "A kinder acid glow for dryness and dullness without a peel hangover.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dullness", "texture", "dryness", "fine-lines"],
  },
  {
    id: "sunday-riley-good-genes",
    name: "Good Genes Lactic Acid Treatment",
    brand: "Sunday Riley",
    area: "skin",
    category: "Lactic treatment",
    step: "exfoliant",
    budget: "splurge",
    lookFor: ["purified lactic acid", "licorice", "evening glow"],
    why: "A cushioned lactic treatment when dullness is the main complaint.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dullness", "texture", "fine-lines", "dark-spots"],
  },
  {
    id: "cosrx-bha-power",
    name: "BHA Blackhead Power Liquid",
    brand: "COSRX",
    area: "skin",
    category: "BHA toner",
    step: "exfoliant",
    budget: "drugstore",
    lookFor: ["betaine salicylate", "willow bark", "gentle BHA"],
    why: "A softer BHA for pores when a 2% liquid feels like too much.",
    skinTypes: ["combination", "oily", "normal"],
    skinConcerns: ["pores", "texture", "acne"],
  },

  // —— Skin · Treatments / serums ——
  {
    id: "to-niacinamide",
    name: "Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    area: "skin",
    category: "Niacinamide serum",
    step: "treat",
    budget: "drugstore",
    lookFor: ["niacinamide 10%", "zinc PCA", "oil-control"],
    why: "A budget workhorse for shine, pores, and leftover marks.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["oiliness", "pores", "acne", "dark-spots"],
  },
  {
    id: "good-molecules-discoloration",
    name: "Discoloration Correcting Serum",
    brand: "Good Molecules",
    area: "skin",
    category: "Brightening serum",
    step: "treat",
    budget: "drugstore",
    lookFor: ["tranexamic acid", "niacinamide", "alpha arbutin"],
    why: "Spot-fading chemistry without a department-store receipt.",
    skinTypes: ["normal", "combination", "oily", "dry"],
    skinConcerns: ["dark-spots", "dullness"],
  },
  {
    id: "to-azelaic",
    name: "Azelaic Acid Suspension 10%",
    brand: "The Ordinary",
    area: "skin",
    category: "Azelaic treatment",
    step: "treat",
    budget: "drugstore",
    lookFor: ["azelaic acid 10%", "redness-friendly", "texture"],
    why: "A quiet multi-tasker for redness, bumps, and leftover pigment.",
    skinTypes: ["sensitive", "combination", "oily", "normal"],
    skinConcerns: ["redness", "acne", "texture", "dark-spots"],
  },
  {
    id: "skinceuticals-ce-ferulic",
    name: "C E Ferulic",
    brand: "SkinCeuticals",
    area: "skin",
    category: "Vitamin C antioxidant",
    step: "treat",
    budget: "splurge",
    lookFor: ["L-ascorbic acid 15%", "vitamin E", "ferulic acid"],
    why: "The gold-standard morning antioxidant when dullness and lines lead.",
    skinTypes: ["normal", "dry", "combination"],
    skinConcerns: ["fine-lines", "dullness", "dark-spots"],
    avoidSkinTypes: ["sensitive"],
  },
  {
    id: "timeless-vit-c",
    name: "20% Vitamin C + E + Ferulic Acid Serum",
    brand: "Timeless",
    area: "skin",
    category: "Vitamin C serum",
    step: "treat",
    budget: "drugstore",
    lookFor: ["L-ascorbic acid 20%", "ferulic acid", "airless / opaque"],
    why: "A close cousin of the cult C serum at a drugstore-adjacent price.",
    skinTypes: ["normal", "combination", "dry", "oily"],
    skinConcerns: ["dullness", "dark-spots", "fine-lines"],
  },
  {
    id: "glow-recipe-guava-c",
    name: "Guava Vitamin C Dark Spot Serum",
    brand: "Glow Recipe",
    area: "skin",
    category: "Vitamin C serum",
    step: "treat",
    budget: "mid",
    lookFor: ["vitamin C", "tranexamic acid", "niacinamide"],
    why: "A juicy brightener for spots and gray-cast skin that still likes hydration.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dark-spots", "dullness"],
  },
  {
    id: "inkey-retinol",
    name: "Retinol Serum",
    brand: "The INKEY List",
    area: "skin",
    category: "Beginner retinol",
    step: "treat-night",
    budget: "drugstore",
    lookFor: ["retinol 1% encapsulated", "slow start", "night only"],
    why: "A measured night retinoid for texture and lines if you are not already using one.",
    skinTypes: ["normal", "combination", "oily", "dry"],
    skinConcerns: ["fine-lines", "texture", "pores", "acne"],
    avoidSkinTypes: ["sensitive"],
  },
  {
    id: "differin-gel",
    name: "Adapalene Gel 0.1%",
    brand: "Differin",
    area: "skin",
    category: "Retinoid gel",
    step: "treat-night",
    budget: "drugstore",
    lookFor: ["adapalene 0.1%", "pea size", "night", "moisturizer sandwich"],
    why: "The over-the-counter retinoid to keep in rotation for stubborn breakouts.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["acne", "texture", "pores"],
    avoidSkinTypes: ["sensitive"],
  },
  {
    id: "dieux-instant-angel",
    name: "Instant Angel",
    brand: "Dieux",
    area: "skin",
    category: "Barrier serum-cream",
    step: "treat",
    budget: "mid",
    lookFor: ["ceramides", "cholesterol", "fatty acids", "peptide"],
    why: "Barrier math for dryness, sting, and over-exfoliated skin.",
    skinTypes: ["dry", "sensitive", "normal"],
    skinConcerns: ["dryness", "redness", "fine-lines"],
  },
  {
    id: "krave-great-barrier",
    name: "Great Barrier Relief",
    brand: "Krave Beauty",
    area: "skin",
    category: "Barrier oil-serum",
    step: "treat",
    budget: "mid",
    lookFor: ["tamanu", "niacinamide", "beta-glucan", "soothing"],
    why: "Calms a cranky barrier without sitting like a heavy occlusive.",
    skinTypes: ["sensitive", "dry", "combination", "normal"],
    skinConcerns: ["redness", "dryness"],
  },
  {
    id: "the-ordinary-ha",
    name: "Hyaluronic Acid 2% + B5",
    brand: "The Ordinary",
    area: "skin",
    category: "Hydrating serum",
    step: "hydrate",
    budget: "drugstore",
    lookFor: ["multi-weight HA", "vitamin B5", "damp-skin apply"],
    why: "A water-magnet layer before cream — especially on dry or dull days.",
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    skinConcerns: ["dryness", "dullness", "fine-lines"],
  },
  {
    id: "vichy-mineral-89",
    name: "Minéral 89 Hyaluronic Acid Serum",
    brand: "Vichy",
    area: "skin",
    category: "Hydrating booster",
    step: "hydrate",
    budget: "mid",
    lookFor: ["hyaluronic acid", "volcanic water", "fragrance-free"],
    why: "A springy hydrator under anything, including actives.",
    skinTypes: ["dry", "normal", "sensitive", "combination"],
    skinConcerns: ["dryness", "redness", "dullness"],
  },
  {
    id: "tatcha-dew-mist",
    name: "The Dewy Skin Serum",
    brand: "Tatcha",
    area: "skin",
    category: "Plumping serum",
    step: "hydrate",
    budget: "splurge",
    lookFor: ["hyaluronic acid", "botanical extracts", "dewy finish"],
    why: "A plush hydrating serum when the brief is glow, not matte.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dryness", "dullness", "fine-lines"],
  },

  // —— Skin · Eye ——
  {
    id: "cerave-eye-repair",
    name: "Eye Repair Cream",
    brand: "CeraVe",
    area: "skin",
    category: "Eye cream",
    step: "eye",
    budget: "drugstore",
    lookFor: ["ceramides", "niacinamide", "marine & plant extracts", "fragrance-free"],
    why: "A no-drama eye cream for dryness and shadow without a sting.",
    skinTypes: ["dry", "normal", "sensitive", "combination"],
    skinConcerns: ["dark-circles", "dryness", "fine-lines"],
  },
  {
    id: "inkey-caffeine",
    name: "Caffeine Eye Cream",
    brand: "The INKEY List",
    area: "skin",
    category: "Eye cream",
    step: "eye",
    budget: "drugstore",
    lookFor: ["caffeine", "peptides", "lightweight"],
    why: "A morning tap-in for puff and tired under-eyes.",
    skinConcerns: ["dark-circles"],
  },
  {
    id: "kiehls-avocado-eye",
    name: "Creamy Eye Treatment with Avocado",
    brand: "Kiehl's",
    area: "skin",
    category: "Rich eye cream",
    step: "eye",
    budget: "mid",
    lookFor: ["avocado oil", "shea", "beta-carotene"],
    why: "A cushion for dry under-eyes that crease when they are thirsty.",
    skinTypes: ["dry", "normal", "sensitive"],
    skinConcerns: ["dark-circles", "dryness", "fine-lines"],
  },
  {
    id: "augustinus-the-eye",
    name: "The Eye Cream",
    brand: "Augustinus Bader",
    area: "skin",
    category: "Eye cream",
    step: "eye",
    budget: "splurge",
    lookFor: ["TFC8", "peptides", "rich but elegant"],
    why: "An investment eye cream when fine lines and fatigue share the bill.",
    skinConcerns: ["fine-lines", "dark-circles", "dryness"],
  },

  // —— Skin · Spot ——
  {
    id: "hero-mighty-patch",
    name: "Mighty Patch Original",
    brand: "Hero Cosmetics",
    area: "skin",
    category: "Hydrocolloid patch",
    step: "spot",
    budget: "drugstore",
    lookFor: ["hydrocolloid", "overnight patch", "hands-off"],
    why: "Stops picking and pulls fluid from a raised whitehead overnight.",
    skinConcerns: ["acne"],
  },
  {
    id: "paulas-choice-bp-spot",
    name: "Clear Regular Strength 2.5% BP",
    brand: "Paula's Choice",
    area: "skin",
    category: "Spot treatment",
    step: "spot",
    budget: "mid",
    lookFor: ["benzoyl peroxide 2.5%", "leave-on", "spot or thin layer"],
    why: "A leave-on peroxide that is strong enough without a 10% scorch.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["acne"],
  },

  // —— Skin · Moisturizer ——
  {
    id: "cerave-pm",
    name: "PM Facial Moisturizing Lotion",
    brand: "CeraVe",
    area: "skin",
    category: "Night moisturizer",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["niacinamide", "ceramides", "hyaluronic acid", "fragrance-free"],
    why: "The reliable jar-adjacent lotion that plays well with actives.",
    skinTypes: ["normal", "combination", "oily", "sensitive"],
    skinConcerns: ["dryness", "oiliness", "acne", "redness"],
  },
  {
    id: "cerave-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "CeraVe",
    area: "skin",
    category: "Rich cream",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["ceramides", "petrolatum", "hyaluronic acid", "tub"],
    why: "Occlusive comfort for dry, cold-weather, or retinoid nights.",
    skinTypes: ["dry", "sensitive", "normal"],
    skinConcerns: ["dryness", "redness", "fine-lines"],
    avoidSkinTypes: ["oily"],
  },
  {
    id: "neutrogena-hydroboost",
    name: "Hydro Boost Water Gel",
    brand: "Neutrogena",
    area: "skin",
    category: "Gel moisturizer",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["hyaluronic acid", "oil-free", "gel"],
    why: "Weightless water for oily and combination skin that hates grease.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["oiliness", "pores", "dullness"],
  },
  {
    id: "fab-ultra-repair",
    name: "Ultra Repair Cream",
    brand: "First Aid Beauty",
    area: "skin",
    category: "Comfort cream",
    step: "moisturizer",
    budget: "mid",
    lookFor: ["colloidal oatmeal", "shea", "ceramides", "fragrance-free option"],
    why: "A hug in a tub for dryness and a reactive flush.",
    skinTypes: ["dry", "sensitive", "normal"],
    skinConcerns: ["dryness", "redness"],
  },
  {
    id: "tatcha-dewy-cream",
    name: "The Dewy Skin Cream",
    brand: "Tatcha",
    area: "skin",
    category: "Rich cream",
    step: "moisturizer",
    budget: "splurge",
    lookFor: ["Hadasei-3", "hyaluronic acid", "dewy finish"],
    why: "A glass-skin cream when dryness and dullness want a ritual, not a lotion.",
    skinTypes: ["dry", "normal", "combination"],
    skinConcerns: ["dryness", "dullness", "fine-lines"],
    avoidSkinTypes: ["oily"],
  },
  {
    id: "belif-aqua-bomb",
    name: "The True Cream Aqua Bomb",
    brand: "belif",
    area: "skin",
    category: "Gel-cream",
    step: "moisturizer",
    budget: "mid",
    lookFor: ["herbs", "gel-cream", "fresh finish"],
    why: "A cooling gel-cream that combination skin can wear to work.",
    skinTypes: ["combination", "oily", "normal"],
    skinConcerns: ["oiliness", "dullness"],
  },
  {
    id: "laneige-cream-skin",
    name: "Cream Skin Refiner",
    brand: "Laneige",
    area: "skin",
    category: "Essence-cream",
    step: "hydrate",
    budget: "mid",
    lookFor: ["ceramide", "milk essence", "pat until absorbed"],
    why: "A milky layer that doubles as a drink for dehydrated combination skin.",
    skinTypes: ["dry", "combination", "normal"],
    skinConcerns: ["dryness", "dullness"],
  },
  {
    id: "la-mer-soft-cream",
    name: "The Moisturizing Soft Cream",
    brand: "La Mer",
    area: "skin",
    category: "Luxury cream",
    step: "moisturizer",
    budget: "splurge",
    lookFor: ["Miracle Broth", "sea kelp", "rich emulsion"],
    why: "A ceremonial cream for dry skin that wants cushion and scent-memory.",
    skinTypes: ["dry", "normal"],
    skinConcerns: ["dryness", "fine-lines"],
    avoidSkinTypes: ["oily", "sensitive"],
  },

  // —— Skin · SPF ——
  {
    id: "lrp-anthelios-fluid",
    name: "Anthelios UV Melt-in Milk SPF 60",
    brand: "La Roche-Posay",
    area: "skin",
    category: "Daily SPF",
    step: "spf",
    budget: "mid",
    lookFor: ["broad spectrum SPF 60", "mexoryl", "water resistant"],
    why: "A reliable everyday sunscreen that plays nicely under makeup.",
    skinTypes: ["normal", "combination", "dry", "oily", "sensitive"],
    skinConcerns: ["dark-spots", "fine-lines", "dullness", "redness"],
  },
  {
    id: "beauty-of-joseon-relief-sun",
    name: "Relief Sun : Rice + Probiotics SPF 50+",
    brand: "Beauty of Joseon",
    area: "skin",
    category: "Serum sunscreen",
    step: "spf",
    budget: "drugstore",
    lookFor: ["SPF 50+", "rice extract", "no white cast", "serum texture"],
    why: "The no-cast school sunscreen that most skins actually finish.",
    skinTypes: ["normal", "combination", "dry", "oily"],
    skinConcerns: ["dark-spots", "dullness", "fine-lines"],
  },
  {
    id: "elta-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    area: "skin",
    category: "Tinted-optional SPF",
    step: "spf",
    budget: "mid",
    lookFor: ["zinc oxide", "niacinamide", "hyaluronic acid", "acne-friendly"],
    why: "The clinic favorite for breakouts, pigment, and sensitive days.",
    skinTypes: ["oily", "combination", "sensitive", "normal"],
    skinConcerns: ["acne", "redness", "dark-spots", "oiliness"],
  },
  {
    id: "supergoop-unseen",
    name: "Unseen Sunscreen SPF 40",
    brand: "Supergoop!",
    area: "skin",
    category: "Invisible gel SPF",
    step: "spf",
    budget: "splurge",
    lookFor: ["SPF 40", "primer-like", "oil-free", "no white cast"],
    why: "A clear gel that doubles as primer — for people who skip cream sunscreens.",
    skinTypes: ["oily", "combination", "normal"],
    skinConcerns: ["oiliness", "pores", "dark-spots"],
  },
  {
    id: "cerave-ultra-light-spf",
    name: "Ultra-Light Moisturizing Lotion SPF 30",
    brand: "CeraVe",
    area: "skin",
    category: "Moisturizer + SPF",
    step: "spf",
    budget: "drugstore",
    lookFor: ["SPF 30", "ceramides", "hyaluronic acid", "niacinamide"],
    why: "A one-and-done morning lotion if you want fewer steps, not fewer rules.",
    skinTypes: ["normal", "combination", "oily", "dry"],
    skinConcerns: ["dryness", "oiliness"],
  },

  // —— Hair · Shampoo ——
  {
    id: "ouai-detox",
    name: "Detox Shampoo",
    brand: "OUAI",
    area: "hair",
    category: "Clarifying shampoo",
    step: "shampoo",
    budget: "mid",
    lookFor: ["apple cider vinegar", "chelating", "once a week"],
    why: "A Sunday reset when product and hard water make roots look tired.",
    hairTypes: ["straight", "wavy", "curly"],
    hairConcerns: ["oiliness"],
    scalpTypes: ["oily", "balanced", "flaky"],
  },
  {
    id: "neutrogena-anti-residue",
    name: "Anti-Residue Shampoo",
    brand: "Neutrogena",
    area: "hair",
    category: "Clarifying shampoo",
    step: "shampoo",
    budget: "drugstore",
    lookFor: ["clarifying", "once weekly", "follow with conditioner"],
    why: "A cheap slate-wipe before a mask if buildup is flattening waves.",
    hairTypes: ["straight", "wavy"],
    hairConcerns: ["oiliness"],
    scalpTypes: ["oily", "balanced"],
  },
  {
    id: "heads-shoulders-clinical",
    name: "Clinical Strength Shampoo",
    brand: "Head & Shoulders",
    area: "hair",
    category: "Anti-dandruff shampoo",
    step: "shampoo",
    budget: "drugstore",
    lookFor: ["selenium sulfide 1%", "leave on 3–5 min", "flake care"],
    why: "Pharmacy-strength flake control when the scalp is truly shedding.",
    hairConcerns: ["dandruff"],
    scalpTypes: ["flaky", "oily", "dry"],
  },
  {
    id: "nizoral-ad",
    name: "A-D Anti-Dandruff Shampoo",
    brand: "Nizoral",
    area: "hair",
    category: "Ketoconazole shampoo",
    step: "shampoo",
    budget: "drugstore",
    lookFor: ["ketoconazole 1%", "twice weekly", "medicated"],
    why: "The classic yeast-aware wash for stubborn flakes and itch.",
    hairConcerns: ["dandruff"],
    scalpTypes: ["flaky", "oily"],
  },
  {
    id: "briogeo-scalp-revival",
    name: "Scalp Revival Charcoal + Coconut Oil Micro-exfoliating Shampoo",
    brand: "Briogeo",
    area: "hair",
    category: "Scalp shampoo",
    step: "shampoo",
    budget: "mid",
    lookFor: ["binchotan charcoal", "tea tree", "peppermint", "physical + chemical"],
    why: "A spa-level scalp scrub-wash for flakes and product film.",
    hairConcerns: ["dandruff", "oiliness"],
    scalpTypes: ["flaky", "oily", "balanced"],
  },
  {
    id: "sheamoisture-jbco-shampoo",
    name: "Jamaican Black Castor Oil Strengthen & Restore Shampoo",
    brand: "SheaMoisture",
    area: "hair",
    category: "Sulfate-free shampoo",
    step: "shampoo",
    budget: "drugstore",
    lookFor: ["sulfate-free", "castor oil", "peppermint", "low-poo"],
    why: "A cushioned cleanse that curly and coily hair does not regret.",
    hairTypes: ["curly", "coily", "wavy"],
    hairConcerns: ["dryness", "breakage", "thinning", "damage"],
    scalpTypes: ["dry", "balanced", "sensitive"],
  },
  {
    id: "olaplex-no4",
    name: "No.4 Bond Maintenance Shampoo",
    brand: "Olaplex",
    area: "hair",
    category: "Bond-building shampoo",
    step: "shampoo",
    budget: "splurge",
    lookFor: ["bis-aminopropyl diglycol dimaleate", "repair", "color-safe"],
    why: "A bond-aware wash when bleach, heat, or color has made hair stretchy.",
    hairConcerns: ["damage", "breakage", "color-treated"],
    hairTypes: ["straight", "wavy", "curly", "coily"],
  },
  {
    id: "living-proof-full",
    name: "Full Shampoo",
    brand: "Living Proof",
    area: "hair",
    category: "Volumizing shampoo",
    step: "shampoo",
    budget: "splurge",
    lookFor: ["Healthy Hair Molecule", "weightless", "fine-hair"],
    why: "A density-looking cleanse that does not oil the roots back down.",
    hairTypes: ["straight", "wavy"],
    hairConcerns: ["thinning", "oiliness"],
    scalpTypes: ["oily", "balanced"],
  },
  {
    id: "vanicream-free-clear-shampoo",
    name: "Free & Clear Shampoo",
    brand: "Vanicream",
    area: "hair",
    category: "Sensitive shampoo",
    step: "shampoo",
    budget: "drugstore",
    lookFor: ["fragrance-free", "dye-free", "for sensitive scalps"],
    why: "Nothing extra — the right call when the scalp stings at perfume.",
    scalpTypes: ["sensitive", "dry", "balanced"],
    hairConcerns: ["dandruff"],
  },
  {
    id: "oribe-moisture-shampoo",
    name: "Moisture & Control Shampoo",
    brand: "Oribe",
    area: "hair",
    category: "Hydrating shampoo",
    step: "shampoo",
    budget: "splurge",
    lookFor: ["splitting hairs: no", "moisture", "anti-frizz", "salon"],
    why: "A plush cleanse for waves and curls that frizz in humidity.",
    hairTypes: ["wavy", "curly", "coily"],
    hairConcerns: ["frizz", "dryness", "color-treated"],
  },
  {
    id: "verb-ghost-shampoo",
    name: "Ghost Shampoo",
    brand: "Verb",
    area: "hair",
    category: "Lightweight shampoo",
    step: "shampoo",
    budget: "mid",
    lookFor: ["weightless", "color-safe", "fine to medium"],
    why: "A see-through cleanse that does not flatten straight or wavy hair.",
    hairTypes: ["straight", "wavy"],
    hairConcerns: ["oiliness", "thinning"],
    scalpTypes: ["oily", "balanced"],
  },

  // —— Hair · Conditioner / mask ——
  {
    id: "sheamoisture-jbco-cond",
    name: "Jamaican Black Castor Oil Strengthen & Restore Conditioner",
    brand: "SheaMoisture",
    area: "hair",
    category: "Rinse-out conditioner",
    step: "conditioner",
    budget: "drugstore",
    lookFor: ["castor oil", "shea", "detangle", "slip"],
    why: "Slip for coils and curls so the comb is not a breakage event.",
    hairTypes: ["curly", "coily", "wavy"],
    hairConcerns: ["dryness", "breakage", "damage"],
  },
  {
    id: "pantene-miracle-cond",
    name: "Miracle Rescue Deep Conditioner",
    brand: "Pantene",
    area: "hair",
    category: "Deep conditioner",
    step: "mask",
    budget: "drugstore",
    lookFor: ["bond repair story", "weekly mask", "drugstore"],
    why: "A surprisingly rich mask when damage is real and the budget is not.",
    hairConcerns: ["damage", "breakage", "dryness"],
    hairTypes: ["straight", "wavy", "curly"],
  },
  {
    id: "olaplex-no3",
    name: "No.3 Hair Perfector",
    brand: "Olaplex",
    area: "hair",
    category: "Bond treatment",
    step: "mask",
    budget: "splurge",
    lookFor: ["pre-shampoo treatment", "10+ minutes", "bond building"],
    why: "The at-home bond step to park on bleach-stretched or crispy hair.",
    hairConcerns: ["damage", "breakage", "color-treated"],
  },
  {
    id: "briogeo-dont-despair",
    name: "Don't Despair, Repair! Deep Conditioning Mask",
    brand: "Briogeo",
    area: "hair",
    category: "Repair mask",
    step: "mask",
    budget: "mid",
    lookFor: ["rosehip", "B vitamins", "vegan", "weekly"],
    why: "A weekly mask that actually feels like it puts protein and slip back.",
    hairConcerns: ["damage", "dryness", "breakage", "color-treated"],
  },
  {
    id: "pattern-heavy-cond",
    name: "Heavy Conditioner",
    brand: "Pattern",
    area: "hair",
    category: "Rich conditioner",
    step: "conditioner",
    budget: "mid",
    lookFor: ["shea", "honey", "coily-friendly", "detangle"],
    why: "Built for 4C–3C density — not a fine-hair conditioner in disguise.",
    hairTypes: ["coily", "curly"],
    hairConcerns: ["dryness", "breakage", "frizz"],
  },
  {
    id: "living-proof-cond",
    name: "Full Conditioner",
    brand: "Living Proof",
    area: "hair",
    category: "Lightweight conditioner",
    step: "conditioner",
    budget: "splurge",
    lookFor: ["weightless", "fine hair", "lengths only"],
    why: "Conditioner that stops at the mid-lengths so roots keep air.",
    hairTypes: ["straight", "wavy"],
    hairConcerns: ["thinning", "oiliness"],
  },
  {
    id: "gvp-conditioning-balm",
    name: "Conditioning Balm",
    brand: "Giovanni",
    area: "hair",
    category: "Rinse-out conditioner",
    step: "conditioner",
    budget: "drugstore",
    lookFor: ["smooth as silk", "slip", "drugstore"],
    why: "A classic detangler that wavy and straight hair can actually rinse clean.",
    hairTypes: ["straight", "wavy", "curly"],
    hairConcerns: ["dryness", "frizz"],
  },

  // —— Hair · Leave-in / oil / style ——
  {
    id: "k18-leavein",
    name: "Leave-In Molecular Repair Hair Mask",
    brand: "K18",
    area: "hair",
    category: "Leave-in peptide mask",
    step: "leavein",
    budget: "splurge",
    lookFor: ["K18Peptide", "4 min", "no rinse", "after shampoo"],
    why: "A peptide leave-in when breakage is the headline, not just dryness.",
    hairConcerns: ["damage", "breakage", "color-treated"],
  },
  {
    id: "its-a-10-leavein",
    name: "Miracle Leave-In Product",
    brand: "It's a 10",
    area: "hair",
    category: "Leave-in spray",
    step: "leavein",
    budget: "mid",
    lookFor: ["heat protectant", "detangle", "spray"],
    why: "The multi-tool spray for heat days and knotty mid-lengths.",
    hairTypes: ["straight", "wavy", "curly"],
    hairConcerns: ["damage", "frizz", "dryness", "color-treated"],
  },
  {
    id: "cantu-leavein",
    name: "Coconut Curling Cream / Leave-In",
    brand: "Cantu",
    area: "hair",
    category: "Curl cream",
    step: "leavein",
    budget: "drugstore",
    lookFor: ["shea", "coconut", "curl definition", "prayer hands"],
    why: "A dense cream that curly and coily hair can actually feel.",
    hairTypes: ["curly", "coily"],
    hairConcerns: ["dryness", "frizz", "breakage"],
  },
  {
    id: "ouidad-climate-control",
    name: "Climate Control Heat & Humidity Gel",
    brand: "Ouidad",
    area: "hair",
    category: "Anti-frizz gel",
    step: "style",
    budget: "mid",
    lookFor: ["humidity shield", "gel", "scrunch"],
    why: "The gel that keeps waves and curls from blooming into a cloud.",
    hairTypes: ["wavy", "curly"],
    hairConcerns: ["frizz"],
  },
  {
    id: "colorwow-dreamcoat",
    name: "Dream Coat Supernatural Spray",
    brand: "Color Wow",
    area: "hair",
    category: "Anti-humidity spray",
    step: "style",
    budget: "splurge",
    lookFor: ["heat-activated", "glass hair", "humidity"],
    why: "A blow-dry seal for straight and wavy hair that frizzes the second it rains.",
    hairTypes: ["straight", "wavy"],
    hairConcerns: ["frizz", "color-treated"],
  },
  {
    id: "the-ordinary-multi-peptide-hair",
    name: "Multi-Peptide Serum for Hair Density",
    brand: "The Ordinary",
    area: "hair",
    category: "Scalp density serum",
    step: "scalp-treat",
    budget: "drugstore",
    lookFor: ["peptides", "scalp apply", "consistent use"],
    why: "A nightly scalp serum when the part is looking see-through.",
    hairConcerns: ["thinning"],
    scalpTypes: ["balanced", "dry", "oily", "sensitive"],
  },
  {
    id: "rogaine-minoxidil",
    name: "Minoxidil 5% Foam",
    brand: "Women's / Men's Rogaine",
    area: "hair",
    category: "Minoxidil",
    step: "scalp-treat",
    budget: "mid",
    lookFor: ["minoxidil 5%", "foam", "daily", "FDA-labeled"],
    why: "The evidence-backed option if thinning is more than a styling problem.",
    hairConcerns: ["thinning"],
  },
  {
    id: "olaplex-no7",
    name: "No.7 Bonding Oil",
    brand: "Olaplex",
    area: "hair",
    category: "Finishing oil",
    step: "oil",
    budget: "splurge",
    lookFor: ["bonding oil", "heat protection", "shine"],
    why: "A few drops on ends for shine without a grease halo.",
    hairConcerns: ["damage", "dryness", "color-treated", "frizz"],
  },
  {
    id: "garnier-hair-food-banana",
    name: "Hair Food Banana 3-in-1",
    brand: "Garnier",
    area: "hair",
    category: "Mask / leave-in",
    step: "mask",
    budget: "drugstore",
    lookFor: ["banana", "3-in-1", "dry hair"],
    why: "A cheerful drugstore mask when dryness is the only complaint.",
    hairConcerns: ["dryness", "frizz"],
    hairTypes: ["wavy", "curly", "straight"],
  },
  {
    id: "amika-perk-up",
    name: "Perk Up Dry Shampoo",
    brand: "amika",
    area: "hair",
    category: "Dry shampoo",
    step: "style",
    budget: "mid",
    lookFor: ["rice starch", "dry shampoo", "day-two"],
    why: "Day-two volume for oily roots without a cloud of white.",
    hairConcerns: ["oiliness"],
    scalpTypes: ["oily"],
    hairTypes: ["straight", "wavy"],
  },
  {
    id: "batiste-original",
    name: "Original Dry Shampoo",
    brand: "Batiste",
    area: "hair",
    category: "Dry shampoo",
    step: "style",
    budget: "drugstore",
    lookFor: ["absorb oil", "spray", "cheap day-two"],
    why: "The backpack dry shampoo when roots collapse before you do.",
    hairConcerns: ["oiliness"],
    scalpTypes: ["oily"],
  },

  // —— Body · Wash ——
  {
    id: "dove-deep-moisture",
    name: "Deep Moisture Body Wash",
    brand: "Dove",
    area: "body",
    category: "Cream body wash",
    step: "wash",
    budget: "drugstore",
    lookFor: ["moisturizing", "sulfate-gentle", "daily"],
    why: "A non-squeaky wash so the towel is not your first moisturizer.",
    bodyConcerns: ["dryness", "none", "rough-patches"],
  },
  {
    id: "vanicream-body-wash",
    name: "Gentle Body Wash",
    brand: "Vanicream",
    area: "body",
    category: "Sensitive body wash",
    step: "wash",
    budget: "drugstore",
    lookFor: ["fragrance-free", "dye-free", "sensitive"],
    why: "The boring (good) wash when scent is the enemy.",
    bodyConcerns: ["dryness", "none"],
  },
  {
    id: "lrp-lipikar-wash",
    name: "Lipikar AP+ Gentle Foaming Moisturizing Wash",
    brand: "La Roche-Posay",
    area: "body",
    category: "Barrier body wash",
    step: "wash",
    budget: "mid",
    lookFor: ["niacinamide", "shea", "fragrance-controlled"],
    why: "A dermatologist-aisle wash for bodies that itch after a hot shower.",
    bodyConcerns: ["dryness", "rough-patches"],
  },
  {
    id: "native-body-wash",
    name: "Body Wash",
    brand: "Native",
    area: "body",
    category: "Everyday body wash",
    step: "wash",
    budget: "mid",
    lookFor: ["clean-scent options", "daily", "simple surfactants"],
    why: "A straightforward wash when odor is the main brief and skin is fine.",
    bodyConcerns: ["odor", "none"],
  },
  {
    id: "necessaire-eucalyptus",
    name: "The Body Wash Eucalyptus",
    brand: "Nécessaire",
    area: "body",
    category: "Niacinamide body wash",
    step: "wash",
    budget: "splurge",
    lookFor: ["niacinamide", "vitamin C", "vitamin E", "omega fatty acids"],
    why: "A considered wash that still feels like a shower, not a lab.",
    bodyConcerns: ["odor", "dryness", "uneven-tone", "none"],
  },

  // —— Body · Exfoliant ——
  {
    id: "cerave-sa-smoother",
    name: "SA Lotion for Rough & Bumpy Skin",
    brand: "CeraVe",
    area: "body",
    category: "BHA body lotion",
    step: "exfoliant",
    budget: "drugstore",
    lookFor: ["salicylic acid", "ceramides", "lactic acid", "KP"],
    why: "The standard answer for strawberry skin, ingrowns, and sandpaper legs.",
    bodyConcerns: ["keratosis", "ingrown", "rough-patches", "uneven-tone"],
  },
  {
    id: "amlactin-daily",
    name: "Daily Moisturizing Body Lotion",
    brand: "AmLactin",
    area: "body",
    category: "Lactic acid lotion",
    step: "exfoliant",
    budget: "drugstore",
    lookFor: ["lactic acid 12%", "ammonium lactate", "night apply"],
    why: "A lactic workhorse for rough elbows, KP, and ashy texture.",
    bodyConcerns: ["keratosis", "rough-patches", "dryness", "uneven-tone"],
  },
  {
    id: "first-aid-kp-bump",
    name: "KP Bump Eraser Body Scrub",
    brand: "First Aid Beauty",
    area: "body",
    category: "Physical + chemical scrub",
    step: "exfoliant",
    budget: "mid",
    lookFor: ["pumice", "glycolic + lactic", "2–3x week"],
    why: "A controlled scrub for arms and thighs that need both grit and acid.",
    bodyConcerns: ["keratosis", "rough-patches", "ingrown"],
  },
  {
    id: "sdj-bum-bum",
    name: "Brazilian Bum Bum Cream",
    brand: "Sol de Janeiro",
    area: "body",
    category: "Firming cream",
    step: "treat",
    budget: "mid",
    lookFor: ["guarana", "guava", "massage", "scented ritual"],
    why: "A mood-lifting cream for stretch-mark massage — not a medical fix.",
    bodyConcerns: ["stretch-marks", "dryness", "none"],
  },
  {
    id: "bio-oil",
    name: "Skincare Oil",
    brand: "Bio-Oil",
    area: "body",
    category: "Body oil",
    step: "treat",
    budget: "drugstore",
    lookFor: ["purcellin oil", "massage twice daily", "scars & marks"],
    why: "A classic massage oil for marks you want to keep supple.",
    bodyConcerns: ["stretch-marks", "uneven-tone", "dryness"],
  },
  {
    id: "palmers-cocoa",
    name: "Cocoa Butter Formula Massage Lotion / Oil",
    brand: "Palmer's",
    area: "body",
    category: "Cocoa butter",
    step: "treat",
    budget: "drugstore",
    lookFor: ["cocoa butter", "vitamin E", "massage"],
    why: "The grocery-aisle stretch-mark ritual that still earns a spot.",
    bodyConcerns: ["stretch-marks", "dryness"],
  },

  // —— Body · Moisturizer / SPF ——
  {
    id: "cerave-daily-lotion",
    name: "Daily Moisturizing Lotion",
    brand: "CeraVe",
    area: "body",
    category: "Body lotion",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["ceramides", "hyaluronic acid", "fragrance-free"],
    why: "The default body cream: cheap, bland, and actually used.",
    bodyConcerns: ["dryness", "none", "rough-patches"],
  },
  {
    id: "eucerin-advanced-repair",
    name: "Advanced Repair Cream",
    brand: "Eucerin",
    area: "body",
    category: "Urea cream",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["urea", "ceramides", "fragrance-free"],
    why: "Urea is the unsung hero for thick, cracked, winter skin.",
    bodyConcerns: ["dryness", "rough-patches"],
  },
  {
    id: "aveeno-oat-lotion",
    name: "Daily Moisturizing Lotion",
    brand: "Aveeno",
    area: "body",
    category: "Oat lotion",
    step: "moisturizer",
    budget: "drugstore",
    lookFor: ["colloidal oatmeal", "dimethicone", "everyday"],
    why: "Oat comfort when the body is itchy more than scaly.",
    bodyConcerns: ["dryness", "none"],
  },
  {
    id: "necessaire-body-lotion",
    name: "The Body Lotion",
    brand: "Nécessaire",
    area: "body",
    category: "Niacinamide body lotion",
    step: "moisturizer",
    budget: "splurge",
    lookFor: ["niacinamide", "omega fatty acids", "fast-absorbing"],
    why: "A silky adult lotion that does not feel like summer-camp sunscreen.",
    bodyConcerns: ["dryness", "uneven-tone", "none"],
  },
  {
    id: "weleda-skin-food",
    name: "Skin Food Original",
    brand: "Weleda",
    area: "body",
    category: "Balm",
    step: "moisturizer",
    budget: "mid",
    lookFor: ["pansy", "calendula", "rich balm", "elbows"],
    why: "A pocket balm for elbows, cuticles, and any patch that laughs at lotion.",
    bodyConcerns: ["rough-patches", "dryness"],
  },
  {
    id: "isdin-eryfotona-body",
    name: "Eryfotona Actinica / mineral body SPF",
    brand: "ISDIN",
    area: "body",
    category: "Body SPF",
    step: "spf",
    budget: "splurge",
    lookFor: ["mineral SPF", "DNA repair enzymes", "body + chest"],
    why: "A serious body sunscreen for chests and arms that hold pigment.",
    bodyConcerns: ["uneven-tone"],
  },
  {
    id: "banana-boat-mineral",
    name: "Mineral / Sheer Protect SPF 50",
    brand: "Banana Boat or Neutrogena Beach Defense",
    area: "body",
    category: "Body SPF",
    step: "spf",
    budget: "drugstore",
    lookFor: ["broad spectrum SPF 50", "water resistant", "body"],
    why: "The beach bottle that still belongs on a pigment-prone collarbone.",
    bodyConcerns: ["uneven-tone", "none"],
  },
  {
    id: "secret-clinical",
    name: "Clinical Strength Antiperspirant",
    brand: "Secret or Certain Dri",
    area: "body",
    category: "Antiperspirant",
    step: "treat",
    budget: "drugstore",
    lookFor: ["aluminum zirconium", "night apply", "clinical"],
    why: "A clinical deodorant step when odor is a sweat problem, not a soap problem.",
    bodyConcerns: ["odor"],
  },
  {
    id: "lume-whole-body",
    name: "Whole Body Deodorant",
    brand: "Lume",
    area: "body",
    category: "Acid deodorant",
    step: "treat",
    budget: "mid",
    lookFor: ["mandelic acid", "whole body", "odor control"],
    why: "An acid deodorant for places regular sticks were never invited.",
    bodyConcerns: ["odor"],
  },
  {
    id: "topicals-faded-body",
    name: "Faded Serum (body-safe use on marks)",
    brand: "Topicals",
    area: "body",
    category: "Brightening serum",
    step: "treat",
    budget: "mid",
    lookFor: ["tranexamic", "niacinamide", "kojic", "spot apply"],
    why: "A mark-fading serum for body leftover pigment — sunscreen still required.",
    bodyConcerns: ["uneven-tone"],
  },
];
